Update rails-controller-testing
This helps, but tests still fail in `test/test_helper.rb` line 184
because "session" is Nil. For example:

~~~~
Error:
UsersEditTest#test_successful_edit_-_password:
NoMethodError: undefined method `session' for nil:NilClass
    test/test_helper.rb:184:in `log_in_as'
    test/integration/users_edit_test.rb:75:in `block in <class:UsersEditTest>'
~~~~

Signed-off-by: David A. Wheeler <dwheeler@dwheeler.com>